version: '3'
services:
  db-task:
    image: mariadb:10.6.13
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db-task:/var/lib/mysql

  webserver-task:
    image: nginx:alpine
    container_name: webserver-task
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "91:80"
  task-php-fpm:
    image: bitnami/php-fpm:8.2.4
    container_name: task-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-ini-override.ini:/opt/bitnami/php/etc/php.ini

volumes:
  my-db-task:
